import { normalizeTask } from './completion';
import { isCalendarDate } from './due';
import type { BacklogItem, Project, Resource, Root, Subtask, Task } from './schema';

/**
 * Every change to the data, as pure functions: (root, …, now) => new root.
 * Ids are generated by the caller so these stay deterministic and testable.
 * Any change inside a project bumps that project's `updatedAt` (merge uses it);
 * any change to a task bumps the task's `updatedAt` (staleness uses it).
 */

export type ResourceInput = { header: string; url: string; note?: string };
/** Where a resource lives: on a project, or on one of its tasks. */
export type ResourceTarget = { projectId: string; taskId?: string };

const clean = (s: string | undefined) => {
  const t = s?.trim();
  return t ? t : undefined;
};

/** Returns a copy of `obj` with `key` set, or removed when the value is empty. */
function withOptional<T extends object, K extends keyof T>(obj: T, key: K, value: string | undefined): T {
  const copy = { ...obj };
  const v = clean(value);
  if (v === undefined) delete copy[key];
  else (copy as Record<K, unknown>)[key] = v;
  return copy;
}

// ─── Projects ────────────────────────────────────────────────────────────────

export function createProject(root: Root, id: string, name: string, now: string): Root {
  const project: Project = {
    id,
    name: name.trim(),
    archived: false,
    createdAt: now,
    updatedAt: now,
    tasks: [],
    resources: [],
  };
  return { ...root, projects: [...root.projects, project] };
}

function mapProject(root: Root, projectId: string, fn: (p: Project) => Project): Root {
  return {
    ...root,
    projects: root.projects.map((p) => (p.id === projectId ? fn(p) : p)),
  };
}

export function renameProject(root: Root, projectId: string, name: string, now: string): Root {
  const n = name.trim();
  if (!n) return root;
  return mapProject(root, projectId, (p) => ({ ...p, name: n, updatedAt: now }));
}

export function setProjectDescription(root: Root, projectId: string, description: string, now: string): Root {
  return mapProject(root, projectId, (p) => ({ ...withOptional(p, 'description', description), updatedAt: now }));
}

export function setProjectArchived(root: Root, projectId: string, archived: boolean, now: string): Root {
  return mapProject(root, projectId, (p) => ({ ...p, archived, updatedAt: now }));
}

/** `due` is a calendar day ("2026-10-03"); empty or undefined clears it. */
export function setProjectDue(root: Root, projectId: string, due: string | undefined, now: string): Root {
  if (due && !isCalendarDate(due)) return root;
  return mapProject(root, projectId, (p) => ({ ...withOptional(p, 'due', due), updatedAt: now }));
}

export function deleteProject(root: Root, projectId: string): Root {
  return {
    ...root,
    projects: root.projects.filter((p) => p.id !== projectId),
    // A suggestion pointing at a deleted project would only mislead.
    backlog: root.backlog.map((b) => {
      if (b.suggestedProjectId !== projectId) return b;
      const { suggestedProjectId: _, ...rest } = b;
      return rest;
    }),
  };
}

// ─── Tasks ───────────────────────────────────────────────────────────────────

function mapTask(root: Root, projectId: string, taskId: string, now: string, fn: (t: Task) => Task): Root {
  return mapProject(root, projectId, (p) => ({
    ...p,
    updatedAt: now,
    tasks: p.tasks.map((t) => (t.id === taskId ? normalizeTask({ ...fn(t), updatedAt: now }, now) : t)),
  }));
}

export function addTask(root: Root, projectId: string, id: string, title: string, now: string): Root {
  const task: Task = {
    id,
    title: title.trim(),
    done: false,
    createdAt: now,
    updatedAt: now,
    subtasks: [],
    resources: [],
  };
  return mapProject(root, projectId, (p) => ({ ...p, updatedAt: now, tasks: [...p.tasks, task] }));
}

export function renameTask(root: Root, projectId: string, taskId: string, title: string, now: string): Root {
  const t = title.trim();
  if (!t) return root;
  return mapTask(root, projectId, taskId, now, (task) => ({ ...task, title: t }));
}

export function setTaskNotes(root: Root, projectId: string, taskId: string, notes: string, now: string): Root {
  return mapTask(root, projectId, taskId, now, (task) => withOptional(task, 'notes', notes));
}

/** `due` is a calendar day ("2026-10-03"); empty or undefined clears it. */
export function setTaskDue(root: Root, projectId: string, taskId: string, due: string | undefined, now: string): Root {
  if (due && !isCalendarDate(due)) return root;
  return mapTask(root, projectId, taskId, now, (task) => withOptional(task, 'due', due));
}

export function deleteTask(root: Root, projectId: string, taskId: string, now: string): Root {
  return mapProject(root, projectId, (p) => ({
    ...p,
    updatedAt: now,
    tasks: p.tasks.filter((t) => t.id !== taskId),
  }));
}

/**
 * Tick or untick a task. With sub-tasks, ticking completes every sub-task and
 * unticking reopens all of them (the UI confirms that first).
 */
export function setTaskDone(root: Root, projectId: string, taskId: string, done: boolean, now: string): Root {
  return mapTask(root, projectId, taskId, now, (task) => {
    if (task.subtasks.length === 0) {
      const { doneAt: _, ...rest } = task;
      return done ? { ...rest, done: true, doneAt: now } : { ...rest, done: false };
    }
    return {
      ...task,
      subtasks: task.subtasks.map((s) => setSubtaskDoneValue(s, done, now)),
    };
  });
}

// ─── Sub-tasks ───────────────────────────────────────────────────────────────

function setSubtaskDoneValue(s: Subtask, done: boolean, now: string): Subtask {
  if (s.done === done) return s;
  const { doneAt: _, ...rest } = s;
  return done ? { ...rest, done: true, doneAt: now } : { ...rest, done: false };
}

function mapSubtask(
  root: Root,
  projectId: string,
  taskId: string,
  subtaskId: string,
  now: string,
  fn: (s: Subtask) => Subtask,
): Root {
  return mapTask(root, projectId, taskId, now, (t) => ({
    ...t,
    subtasks: t.subtasks.map((s) => (s.id === subtaskId ? fn(s) : s)),
  }));
}

export function addSubtask(root: Root, projectId: string, taskId: string, id: string, title: string, now: string): Root {
  const subtask: Subtask = { id, title: title.trim(), done: false };
  return mapTask(root, projectId, taskId, now, (t) => ({ ...t, subtasks: [...t.subtasks, subtask] }));
}

export function setSubtaskDone(
  root: Root,
  projectId: string,
  taskId: string,
  subtaskId: string,
  done: boolean,
  now: string,
): Root {
  return mapSubtask(root, projectId, taskId, subtaskId, now, (s) => setSubtaskDoneValue(s, done, now));
}

export function renameSubtask(
  root: Root,
  projectId: string,
  taskId: string,
  subtaskId: string,
  title: string,
  now: string,
): Root {
  const t = title.trim();
  if (!t) return root;
  return mapSubtask(root, projectId, taskId, subtaskId, now, (s) => ({ ...s, title: t }));
}

export function setSubtaskDue(
  root: Root,
  projectId: string,
  taskId: string,
  subtaskId: string,
  due: string | undefined,
  now: string,
): Root {
  if (due && !isCalendarDate(due)) return root;
  return mapSubtask(root, projectId, taskId, subtaskId, now, (s) => withOptional(s, 'due', due));
}

export function deleteSubtask(root: Root, projectId: string, taskId: string, subtaskId: string, now: string): Root {
  return mapTask(root, projectId, taskId, now, (t) => ({
    ...t,
    subtasks: t.subtasks.filter((s) => s.id !== subtaskId),
  }));
}

// ─── Resources ───────────────────────────────────────────────────────────────

function mapResources(root: Root, target: ResourceTarget, now: string, fn: (rs: Resource[]) => Resource[]): Root {
  if (target.taskId) {
    return mapTask(root, target.projectId, target.taskId, now, (t) => ({ ...t, resources: fn(t.resources) }));
  }
  return mapProject(root, target.projectId, (p) => ({ ...p, updatedAt: now, resources: fn(p.resources) }));
}

/** Keys in schema order, so an import of an export is identical byte for byte. */
function buildResource(id: string, addedAt: string, input: ResourceInput): Resource {
  const note = clean(input.note);
  return { id, header: input.header.trim(), url: input.url.trim(), ...(note ? { note } : {}), addedAt };
}

export function addResource(root: Root, target: ResourceTarget, id: string, input: ResourceInput, now: string): Root {
  const resource = buildResource(id, now, input);
  return mapResources(root, target, now, (rs) => [...rs, resource]);
}

export function updateResource(
  root: Root,
  target: ResourceTarget,
  resourceId: string,
  input: ResourceInput,
  now: string,
): Root {
  return mapResources(root, target, now, (rs) =>
    rs.map((r) => (r.id === resourceId ? buildResource(r.id, r.addedAt, input) : r)),
  );
}

export function deleteResource(root: Root, target: ResourceTarget, resourceId: string, now: string): Root {
  return mapResources(root, target, now, (rs) => rs.filter((r) => r.id !== resourceId));
}

// ─── Backlog ─────────────────────────────────────────────────────────────────

export function addBacklogItem(
  root: Root,
  id: string,
  title: string,
  now: string,
  opts: { notes?: string; suggestedProjectId?: string } = {},
): Root {
  const notes = clean(opts.notes);
  const suggestedProjectId = clean(opts.suggestedProjectId);
  const item: BacklogItem = {
    id,
    title: title.trim(),
    ...(notes ? { notes } : {}),
    ...(suggestedProjectId ? { suggestedProjectId } : {}),
    createdAt: now,
    updatedAt: now,
  };
  return { ...root, backlog: [...root.backlog, item] };
}

function mapBacklog(root: Root, itemId: string, now: string, fn: (b: BacklogItem) => BacklogItem): Root {
  return {
    ...root,
    backlog: root.backlog.map((b) => (b.id === itemId ? { ...fn(b), updatedAt: now } : b)),
  };
}

export function renameBacklogItem(root: Root, itemId: string, title: string, now: string): Root {
  const t = title.trim();
  if (!t) return root;
  return mapBacklog(root, itemId, now, (b) => ({ ...b, title: t }));
}

export function setBacklogNotes(root: Root, itemId: string, notes: string, now: string): Root {
  return mapBacklog(root, itemId, now, (b) => withOptional(b, 'notes', notes));
}

export function deleteBacklogItem(root: Root, itemId: string): Root {
  return { ...root, backlog: root.backlog.filter((b) => b.id !== itemId) };
}

/** Backlog item → open task at the end of the project. Notes come along. */
export function promote(root: Root, itemId: string, projectId: string, now: string): Root {
  const item = root.backlog.find((b) => b.id === itemId);
  if (!item || !root.projects.some((p) => p.id === projectId)) return root;
  const task: Task = {
    id: item.id,
    title: item.title,
    done: false,
    ...(item.notes ? { notes: item.notes } : {}),
    createdAt: now,
    updatedAt: now,
    subtasks: [],
    resources: [],
  };
  const next = mapProject(root, projectId, (p) => ({ ...p, updatedAt: now, tasks: [...p.tasks, task] }));
  return deleteBacklogItem(next, itemId);
}

/** Task → backlog. Sub-tasks and resources are dropped (the UI confirms first). */
export function demote(root: Root, projectId: string, taskId: string, now: string): Root {
  const task = root.projects.find((p) => p.id === projectId)?.tasks.find((t) => t.id === taskId);
  if (!task) return root;
  const next = deleteTask(root, projectId, taskId, now);
  return addBacklogItem(next, task.id, task.title, now, { notes: task.notes, suggestedProjectId: projectId });
}
